export const SERVICOS_VENDIDOS = [
  "DJ",
  "DJ s/ AV",
  "DJ todo o dia",
  "Karaoke s/ AV",
  "Som 1 PA",
  "Som 2 PAs",
  "AV base evento",
  "AV Base",
  "AV Premium",
  "Sax",
  "Violinista",
  "Acordionista",
  "Cantor(a)",
  "Bailarinos s/ receção",
  "Bailarinos c/ receção",
  "Asas Isis (2 bailarinos)",
  "Artista de Fogo",
  "Artista de Malabares",
  "Anão",
  "Show Bolas de Sabão",
  "Mágico(a)",
  "Cubo (a partir de 3m)",
  "Forças Combinadas - dueto",
  "Acro - dueto",
  "Acro Aéreos - solo",
  "Lyra Aéreos - dueto",
  "Straps Aéreos - solo",
  "Straps Aéreos - dueto",
  "Pórtico Aéreos",
  "Spiral - plataforma",
  "Lollipop - plataforma",
  "Chandelier - plataforma",
  "Diamante - plataforma",
  "Animador / Host",
  "Animador Infantil c/ jogos",
  "Make-up & Hair",
  "Guarda Roupa",
  "Produtor",
  "Trio Fado",
  "Annia Solo",
  "Annia Solo c/ AVs",
  "Banda Duo s/ AV",
  "Banda Duo c/ AVs",
  "Banda Trio s/ AV",
  "Banda Trio c/ AVs",
  "Banda quarteto s/ AV",
  "Banda quarteto c/ AVs",
  "Banda quinteto s/ AV",
  "Banda quinteto c/ AVs",
  "Banda quinteto + Cantor",
  "Banda quinteto + Cantor c/ AVs",
  "Banda quinteto + 2 Back Vocals",
  "Banda quinteto + 2 BVs c/ AVs",
  "DJ Booth LED - branco",
  "DJ Booth LED - preto",
  "1 PA Mackie Thump 212 12\"",
  "Mixer Behringer Xenyx 1202SFX",
  "Controller Pioneer Rekordbox DJ DDJ-400",
  "Stairville LED Bar 240/8 RGB DMX 30º",
  "4 Baterias LEDs Uking RGBWA + UV Par Light",
  "8 LEDs Wash 7x12 RGBW",
  "4 LEDs Uking 105W 7x15W RGBW",
  "LED efeito flor Eurolite FE-700",
  "Máquina de fumo Ibiza LSM900W",
  "Microfone c/ fio Sennheiser e835",
  "2 Microfones dual UHF s/ fios GLXD2",
  "1 Shure SM58 s/ fios",
  "Cablagem completa XLR",
  "Discurso",
  "DJ Basic",
  "Let\'s Party",
  "Premium",
  "Serviço sob consulta",
  "Técnico de Som",
  "Técnico de Luz",
  "Deslocações",
  "Aluguer de Carrinha",
] as const;

// Função/serviço executado numa Agenda/Lead por um colaborador.
// Deve ser mais operacional do que a lista comercial de serviços vendidos.
export const ARTIST_TIPOS = [
  "DJ",
  "Karaoke Host",
  "Técnico de Som",
  "Técnico AV",
  "Técnico de Luz",
  "Saxofonista",
  "Violinista",
  "Acordionista",
  "Cantor(a)",
  "Cantor(a) Fado",
  "Guitarra Portuguesa",
  "Viola/Guitarra Fado",
  "Guitarrista",
  "Pianista",
  "Baixista",
  "Baterista",
  "Percussionista",
  "Trompetista",
  "Bailarino(a)",
  "Bailarino(a) Asas Isis",
  "Artista de Fogo",
  "Malabarista",
  "Performer Bolas de Sabão",
  "Mágico(a)",
  "Performer Cubo",
  "Acrobata",
  "Acrobata Aéreo(a)",
  "Performer Lyra",
  "Performer Straps",
  "Performer Plataforma",
  "Técnico de Rigging",
  "Animador / Host",
  "MC",
  "Ator(a)",
  "Animador Infantil",
  "Make-up & Hair",
  "Guarda-Roupa",
  "Produtor",
  "Assistente de Produção",
  "Coreógrafo(a)",
  "Fotógrafo/Videógrafo",
  "Outro",
] as const;

// Skills disponíveis na ficha de colaborador. Mantém-se separado dos serviços vendidos.
export const COLABORADOR_SKILLS = [
  ...ARTIST_TIPOS,
  "Performer Especial",
] as const;

export const MODALIDADES = ["Fatura", "Por Fora", "50% Por Fora", "10% Por Fora"];

export const TIPOS_COMERCIAIS = ["Evento", "Residência", "Evento de Residência", "Cliente Especial"] as const;
export const VALOR_CONTEXTOS = ["Cliente Final", "Parceiro", "Residência", "Evento Residência", "SUD", "SANA", "Hyatt", "Conta Especial"] as const;

// Normalização de nomes de colaboradores/artistas:
// Chave = variante em lowercase → Valor = nome canónico
// Adiciona aqui novas variantes sem tocar noutro código
export const COLABORADOR_ALIASES: Record<string, string> = {
  "antonio": "António",
  "antónio": "António",
  "gio": "João Pereira",
  "joão pereira": "João Pereira",
};

export function resolveColaboradorNome(nome: string): string {
  return COLABORADOR_ALIASES[nome.trim().toLowerCase()] ?? nome.trim();
}
